version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=vehicles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
